FROM ubuntu:22.04

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
      ca-certificates \
      libibverbs1 \
      libnl-3-200 \
      libnl-route-3-200 \
      libyaml-0-2 \
      libsasl2-2 \
      openssl && \
    rm -rf /var/lib/apt/lists/*

COPY bench_dpumesh /usr/local/bin/bench_dpumesh
COPY doca-libs/ /usr/local/lib/
COPY thrift-install/usr/local/lib/libthrift* /usr/local/lib/

RUN ldconfig

ENV LD_LIBRARY_PATH=/usr/local/lib
EXPOSE 9092

ENTRYPOINT ["/usr/local/bin/bench_dpumesh"]
