FROM ubuntu:22.04

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y ca-certificates && \
    rm -rf /var/lib/apt/lists/*

COPY bench_tcp /usr/local/bin/bench_tcp

EXPOSE 9092

ENTRYPOINT ["/usr/local/bin/bench_tcp"]
